"""Explicit permission snapshot. New routes must be added deliberately."""

from __future__ import annotations

from starlette.routing import compile_path

ROUTE_PERMISSIONS: dict[tuple[str, str], str] = {
    ("DELETE", "/api/asset-cards/{asset_id}"): "asset_cards.manage",
    ("DELETE", "/api/asset-groups/{group_id}/overrides/{asset_id}"): "asset_groups.manage",
    ("DELETE", "/api/auth/roles/{role_id}"): "security.roles.manage",
    ("DELETE", "/api/automations/runbooks/{runbook_id}"): "automations.manage",
    ("DELETE", "/api/automations/schedules/{schedule_id}"): "automations.manage",
    ("DELETE", "/api/saved-views/{view_id}"): "saved_views.manage",
    ("DELETE", "/api/scanner-tasks/{task_id}"): "tasks.manage",
    ("DELETE", "/api/vulnerability-passports/{passport_id}"): "passports.manage",
    ("GET", "/api/asset-card-query/fields"): "asset_cards.read",
    ("GET", "/api/asset-card-query/presets"): "asset_cards.read",
    ("GET", "/api/asset-cards/build-jobs/active"): "asset_cards.read",
    ("GET", "/api/asset-cards/build-jobs/{job_id}"): "asset_cards.read",
    ("GET", "/api/asset-cards/local"): "asset_cards.read",
    ("GET", "/api/asset-cards/refresh-scan/templates"): "asset_cards.read",
    ("GET", "/api/asset-cards/{asset_id}"): "asset_cards.read",
    ("GET", "/api/asset-cards/{asset_id}/configuration/detail"): "asset_cards.read",
    ("GET", "/api/asset-cards/{asset_id}/configuration/tree"): "asset_cards.read",
    ("GET", "/api/asset-cards/{asset_id}/history"): "asset_cards.read",
    ("GET", "/api/asset-cards/{asset_id}/summary"): "asset_cards.read",
    ("GET", "/api/asset-cards/{asset_id}/vulnerabilities/findings"): "asset_cards.read",
    ("GET", "/api/asset-cards/{asset_id}/vulnerabilities/groups"): "asset_cards.read",
    ("GET", "/api/asset-groups"): "asset_groups.read",
    ("GET", "/api/asset-groups/precheck-runs"): "asset_groups.read",
    ("GET", "/api/asset-groups/precheck-stats"): "asset_groups.read",
    ("GET", "/api/asset-groups/tree"): "asset_groups.read",
    ("GET", "/api/asset-groups/{group_id}"): "asset_groups.read",
    ("GET", "/api/asset-groups/{group_id}/members"): "asset_groups.read",
    ("GET", "/api/assets"): "assets.read",
    ("GET", "/api/assets/summary"): "assets.read",
    ("GET", "/api/attention"): "system.read",
    ("GET", "/api/auth/audit"): "security.audit.read",
    ("GET", "/api/auth/permissions"): "security.roles.read",
    ("GET", "/api/auth/roles"): "security.roles.read",
    ("GET", "/api/auth/users"): "security.users.read",
    ("GET", "/api/automations/runbooks"): "automations.read",
    ("GET", "/api/automations/runbooks/{runbook_id}"): "automations.read",
    ("GET", "/api/automations/runs"): "automations.read",
    ("GET", "/api/automations/runs/{run_id}"): "automations.read",
    ("GET", "/api/automations/schedules"): "automations.read",
    ("GET", "/api/automations/templates"): "automations.read",
    ("GET", "/api/coverage/assets"): "assets.read",
    ("GET", "/api/coverage/summary"): "assets.read",
    ("GET", "/api/defaults"): "system.read",
    ("GET", "/api/exports/{filename}"): "imports_exports.read",
    ("GET", "/api/mpvm/lookups"): "connection.read",
    ("GET", "/api/mpvm/scanner-tasks/remote"): "connection.read",
    ("GET", "/api/notifications"): "notifications.read",
    ("GET", "/api/operations"): "operations.read",
    ("GET", "/api/operations/summary"): "operations.read",
    ("GET", "/api/operations/{operation_id}"): "operations.read",
    ("GET", "/api/operations/{operation_id}/diagnostics"): "diagnostics.read",
    ("GET", "/api/remediation/campaigns"): "remediation.read",
    ("GET", "/api/remediation/campaigns/{campaign_id}"): "remediation.read",
    ("GET", "/api/remediation/cases"): "remediation.read",
    ("GET", "/api/remediation/cases/{case_id}"): "remediation.read",
    ("GET", "/api/remediation/policy"): "remediation.read",
    ("GET", "/api/remediation/resolution-stats"): "remediation.read",
    ("GET", "/api/remediation/summary"): "remediation.read",
    ("GET", "/api/risk/queue"): "risk.read",
    ("GET", "/api/risk/summary"): "risk.read",
    ("GET", "/api/saved-views"): "saved_views.read",
    ("GET", "/api/scanner-tasks"): "tasks.read",
    ("GET", "/api/scanner-task-folders"): "tasks.read",
    ("GET", "/api/scanner-tasks/{task_id}/runs"): "tasks.read",
    ("GET", "/api/scanner-tasks/{task_id}/runs/{run_id}/jobs"): "tasks.read",
    ("GET", "/api/scanner-tasks/{task_id}/postprocess-runs/latest"): "tasks.read",
    ("GET", "/api/scanner-tasks/{task_id}/results"): "tasks.read",
    ("GET", "/api/search"): "system.read",
    ("GET", "/api/session"): "connection.read",
    ("GET", "/api/system/status"): "system.read",
    ("GET", "/api/vm/overview"): "operations.read",
    ("GET", "/api/vm/workflows"): "operations.read",
    ("GET", "/api/vm/workflows/{workflow_id}"): "operations.read",
    ("GET", "/api/vulnerabilities"): "assets.read",
    ("GET", "/api/vulnerabilities/compliance/{scope}/findings"): "assets.read",
    ("GET", "/api/vulnerabilities/compliance/{scope}/stale-assets"): "assets.read",
    ("GET", "/api/vulnerabilities/compliance/{scope}/summary"): "assets.read",
    ("GET", "/api/vulnerabilities/hosts"): "assets.read",
    ("GET", "/api/vulnerabilities/summary"): "assets.read",
    ("GET", "/api/vulnerabilities/trending"): "assets.read",
    ("GET", "/api/vulnerabilities/trends"): "assets.read",
    ("GET", "/api/vulnerability-passports/detail-jobs/active"): "passports.read",
    ("GET", "/api/vulnerability-passports/detail-jobs/{job_id}"): "passports.read",
    ("GET", "/api/vulnerability-passports/local"): "passports.read",
    ("GET", "/api/vulnerability-passports/refresh-jobs/latest"): "passports.read",
    ("GET", "/api/vulnerability-passports/refresh-jobs/{operation_id}"): "passports.read",
    ("GET", "/api/vulnerability-passports/{passport_id}"): "passports.read",
    ("GET", "/api/vulnerability-passports/{passport_id}/asset-links"): "passports.read",
    ("PATCH", "/api/asset-groups/{group_id}"): "asset_groups.manage",
    ("PATCH", "/api/assets/context"): "risk.manage",
    ("PATCH", "/api/auth/roles/{role_id}"): "security.roles.manage",
    ("PATCH", "/api/auth/users/{user_id}"): "security.users.manage",
    ("PATCH", "/api/remediation/campaigns/{campaign_id}"): "remediation.manage",
    ("PATCH", "/api/remediation/cases/{case_id}"): "remediation.manage",
    ("POST", "/api/asset-card-query"): "asset_cards.read",
    ("POST", "/api/asset-card-query/export"): "imports_exports.read",
    ("POST", "/api/asset-card-query/presets/{preset_id}"): "asset_cards.read",
    ("POST", "/api/asset-card-query/presets/{preset_id}/assets"): "asset_cards.read",
    ("POST", "/api/asset-cards/build"): "asset_cards.build",
    ("POST", "/api/asset-cards/build-jobs"): "asset_cards.build",
    ("POST", "/api/asset-cards/build-jobs/batch"): "asset_cards.build",
    ("POST", "/api/asset-cards/build-jobs/{job_id}/cancel"): "asset_cards.build",
    ("POST", "/api/asset-cards/query-assets"): "asset_cards.read",
    ("POST", "/api/asset-cards/refresh-scan/bulk"): "asset_cards.build",
    ("POST", "/api/asset-cards/{asset_id}/refresh-scan"): "asset_cards.build",
    ("POST", "/api/asset-groups"): "asset_groups.manage",
    ("POST", "/api/asset-groups/bulk-action"): "asset_groups.manage",
    ("POST", "/api/asset-groups/from-vulnerability"): "asset_groups.manage",
    ("POST", "/api/asset-groups/preview"): "asset_groups.manage",
    ("POST", "/api/asset-groups/{group_id}/archive"): "asset_groups.manage",
    ("POST", "/api/asset-groups/{group_id}/evaluate"): "asset_groups.manage",
    ("POST", "/api/asset-groups/{group_id}/scan"): "tasks.execute",
    ("POST", "/api/asset-groups/{group_id}/verify"): "tasks.execute",
    ("POST", "/api/assets/context/import"): "risk.manage",
    ("POST", "/api/auth/roles/clone"): "security.roles.manage",
    ("POST", "/api/auth/users"): "security.users.manage",
    ("POST", "/api/automations/runbooks"): "automations.manage",
    ("POST", "/api/automations/runbooks/{runbook_id}/clone"): "automations.manage",
    ("POST", "/api/automations/runbooks/{runbook_id}/publish"): "automations.manage",
    ("POST", "/api/automations/runbooks/{runbook_id}/run"): "automations.execute",
    ("POST", "/api/automations/runs/{run_id}/cancel"): "automations.execute",
    ("POST", "/api/automations/runs/{run_id}/retry"): "automations.execute",
    ("POST", "/api/automations/schedules"): "automations.manage",
    ("POST", "/api/diagnostics/frontend"): "diagnostics.write",
    ("POST", "/api/exports/pdql"): "imports_exports.manage",
    ("POST", "/api/import/csv-file"): "imports_exports.manage",
    ("POST", "/api/import/csv-text"): "imports_exports.manage",
    ("POST", "/api/import/sample"): "imports_exports.manage",
    ("POST", "/api/notifications/{notification_id}/read"): "notifications.manage",
    ("POST", "/api/operations/{operation_id}/cancel"): "operations.cancel",
    ("POST", "/api/operations/{operation_id}/retry"): "operations.retry",
    ("POST", "/api/remediation/campaigns"): "remediation.manage",
    ("POST", "/api/remediation/campaigns/{campaign_id}/verify"): "remediation.manage",
    ("POST", "/api/remediation/cases/bulk-update"): "remediation.manage",
    ("POST", "/api/remediation/cases/start"): "remediation.manage",
    ("POST", "/api/reports/vulnerabilities/compliance/{scope}/{report_format}"): "imports_exports.read",
    ("POST", "/api/reports/vulnerabilities/xlsx"): "imports_exports.read",
    ("POST", "/api/reports/vulnerabilities/{report_type}/csv"): "imports_exports.read",
    ("POST", "/api/saved-views"): "saved_views.manage",
    ("POST", "/api/scanner-tasks"): "tasks.manage",
    ("POST", "/api/scanner-task-folders"): "tasks.manage",
    ("POST", "/api/scanner-tasks/{task_id}/delete"): "tasks.manage",
    ("POST", "/api/scanner-tasks/{task_id}/retry-false"): "tasks.execute",
    ("POST", "/api/scanner-tasks/{task_id}/start"): "tasks.execute",
    ("POST", "/api/scanner-tasks/{task_id}/stop"): "tasks.execute",
    ("POST", "/api/scanner-tasks/{task_id}/validate"): "tasks.execute",
    ("POST", "/api/session/connect"): "connection.manage",
    ("POST", "/api/session/disconnect"): "connection.manage",
    ("POST", "/api/vm/workflows/scan"): "tasks.execute",
    ("POST", "/api/vm/workflows/scan/preflight"): "tasks.read",
    ("POST", "/api/vm/workflows/{workflow_id}/cancel"): "operations.cancel",
    ("POST", "/api/vm/workflows/{workflow_id}/retry"): "operations.retry",
    ("POST", "/api/vulnerability-passports/detail-jobs/{job_id}/cancel"): "passports.manage",
    ("POST", "/api/vulnerability-passports/query"): "passports.manage",
    ("POST", "/api/vulnerability-passports/refresh-jobs"): "passports.manage",
    ("POST", "/api/vulnerability-passports/refresh-jobs/{operation_id}/cancel"): "passports.manage",
    ("POST", "/api/vulnerability-passports/trending/refresh"): "passports.manage",
    ("PUT", "/api/asset-cards/{asset_id}"): "asset_cards.manage",
    ("PUT", "/api/asset-groups/{group_id}/overrides/{asset_id}"): "asset_groups.manage",
    ("PUT", "/api/automations/runbooks/{runbook_id}"): "automations.manage",
    ("PUT", "/api/automations/schedules/{schedule_id}"): "automations.manage",
    ("PUT", "/api/remediation/policy"): "remediation.policy",
    ("PUT", "/api/scanner-tasks/{task_id}"): "tasks.manage",
    ("PUT", "/api/scanner-task-folders/assignments"): "tasks.manage",
    ("PATCH", "/api/scanner-task-folders/{folder_id}"): "tasks.manage",
    ("DELETE", "/api/scanner-task-folders/{folder_id}"): "tasks.manage",
    ("PUT", "/api/vulnerability-passports/{passport_id}"): "passports.manage",
}

_MATCHERS = [(method, compile_path(path)[0], permission)
             for (method, path), permission in ROUTE_PERMISSIONS.items()]


def required_permission(method: str, path: str) -> str:
    method = method.upper()
    if method == "HEAD":
        method = "GET"
    for allowed_method, pattern, permission in _MATCHERS:
        if allowed_method == method and pattern.fullmatch(path):
            return permission
    return "__deny__"
