import { useCallback, useEffect, useState } from "react";
import { api, createIdempotencyKey } from "../api/client.js";

export function CoveragePage({ showAlert, onNavigate }) {
  const [summary,setSummary]=useState({}); const [rows,setRows]=useState([]); const [loading,setLoading]=useState(true);
  const [filters,setFilters]=useState({q:"",issue:""}); const [error,setError]=useState("");
  const load=useCallback(async()=>{ setLoading(true);setError(""); const p=new URLSearchParams(); if(filters.q)p.set("q",filters.q);if(filters.issue)p.set("issue",filters.issue);
    try { const [totals,items]=await Promise.all([api("/api/coverage/summary"),api(`/api/coverage/assets?${p}`)]);setSummary(totals);setRows(items.rows||[]); }
    catch(next){setError(next.operatorMessage||next.message);}finally{setLoading(false);} },[filters]);
  useEffect(()=>{load();},[load]);
  const refresh=async(item)=>{try{await api("/api/asset-cards/build-jobs",{method:"POST",headers:{"X-Idempotency-Key":createIdempotencyKey("coverage")},body:JSON.stringify({asset_id:item.asset_id})});showAlert("Обновление карточки поставлено в очередь.","success");onNavigate("/operations");}catch(next){showAlert(next.operatorMessage||next.message,"error");}};
  const retry=async(item)=>{try{await api(`/api/operations/${item.operation_id}/retry`,{method:"POST"});showAlert("Операция запущена повторно.","success");onNavigate("/operations");}catch(next){showAlert(next.operatorMessage||next.message,"error");}};
  return <section className="panel coverage-page"><div className="panel__header"><div><h2>Покрытие сканированием</h2><p>Полнота и свежесть локальных карточек активов. Порог устаревания: {summary.stale_days || 7} дней.</p></div><button onClick={load}>Обновить</button></div>
    <div className="metric-grid"><Metric label="Покрытие" value={`${summary.coverage_percent ?? 0}%`} /><Metric label="Активов" value={summary.total_assets}/><Metric label="Без карточки" value={summary.missing_card}/><Metric label="Устарели" value={summary.stale}/><Metric label="Усечены" value={summary.truncated}/><Metric label="Ошибка обновления" value={summary.last_refresh_failed}/></div>
    <div className="remediation-toolbar"><input aria-label="Поиск активов" placeholder="Имя, IP, FQDN" value={filters.q} onChange={(e)=>setFilters({...filters,q:e.target.value})}/><select aria-label="Проблема" value={filters.issue} onChange={(e)=>setFilters({...filters,issue:e.target.value})}><option value="">Все активы</option><option value="missing">Без карточки</option><option value="stale">Устаревшие</option><option value="truncated">Усечённые данные</option><option value="failed">Ошибка обновления</option></select></div>
    {error?<div className="inline-error">{error}</div>:null}<div className="table-shell"><table><thead><tr><th>Актив</th><th>Последние данные</th><th>Состояние</th><th></th></tr></thead><tbody>{loading?<tr><td colSpan="4" className="empty-cell">Загрузка…</td></tr>:rows.map((item)=><tr key={item.asset_id}><td>{item.display_name||item.asset_id}<small>{item.ip_address||item.fqdn}</small></td><td>{formatDate(item.last_seen)}</td><td><div className="issue-list">{item.missing_card?<span>Нет карточки</span>:null}{item.stale?<span>Устарела</span>:null}{item.truncated?<span>Данные усечены</span>:null}{item.last_refresh_failed?<span>Ошибка обновления</span>:null}{!item.missing_card&&!item.stale&&!item.truncated&&!item.last_refresh_failed?<span className="issue-ok">Актуально</span>:null}</div></td><td><button onClick={()=>item.last_refresh_failed&&item.operation_id?retry(item):refresh(item)}>{item.last_refresh_failed&&item.operation_id?"Повторить":"Обновить карточку"}</button></td></tr>)}</tbody></table></div>
  </section>;
}
function Metric({label,value}){return <article className="metric-card"><span>{label}</span><strong>{value??0}</strong></article>;} function formatDate(value){return value?new Intl.DateTimeFormat("ru-RU",{dateStyle:"short",timeStyle:"short"}).format(new Date(value)):"—";}
